### ISSUE TITLE
AplikasiObatMaster

### ISSUE THREAD

**Issue by bayuasdi13** [milstrike/AplikasiObat#7]
@milstrike  salam, saya sudah clone project aplikasi sistem informasi pengelolaan obat, pas login ke aplikasi , error mas? Apa password dan usernamenya yang salah?

**Comment by milstrike** [comment]
Username dan password tersimpan di file db. Silakan untuk menginstall db nya terlebih dahulu. Untuk memformat password silakan ganti password yang tersimpan dengan password yang Anda inginkan dalam format MD5. Untuk memastikan app dapat berjalan dengan baik, silakan untuk menginstall laravel 5 pada php 5.6 terlebih dahulu.

**Comment by bayuasdi13** [comment]
Ada link tutorial installnya mas?

Pada tanggal Sab, 29 Feb 2020 08.38, Muhammad Irfan Luthfi <
notifications@github.com> menulis:

**Comment by milstrike** [comment]
Db bisa langsung diimport via phpmyadmin dan diconfig lewat file config.
